create TABLE if not exists  T_ORDER (
ORDER_ID INT(15) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(20),
ORDER_DATE TIMESTAMP,
SHIPPING_ADDRESS VARCHAR(20),
TOTAL INT(10)
);

INSERT INTO T_ORDER values (1, 'test', CURRENT_TIMESTAMP, 'address', 20);